"""
Artemis_AR FastAPI backend.

Every endpoint reads from the REAL data files already generated by the
pipeline (Days 1-7): invoices.csv, customers.csv, final_audit_trail.csv,
exception_report.csv, gated_run_state.json. Nothing is fabricated or
hardcoded here -- if a file doesn't exist yet, the endpoint says so
explicitly rather than returning fake data.

Run with: uvicorn src.api:app --reload --port 8000
Docs at:  http://localhost:8000/docs
"""

from pathlib import Path
from typing import Optional

import pandas as pd
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from src.state_io import load_states_from_file

DATA_DIR = Path(__file__).resolve().parent.parent / "data"

app = FastAPI(
    title="Artemis_AR API",
    description="B2B receivables (dunning) agent -- real data, real decisions, real audit trail.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # fine for local demo; tighten for real deployment
    allow_methods=["*"],
    allow_headers=["*"],
)


def _require_file(path: Path, hint: str):
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"{path.name} not found. {hint}"
        )


def _sanitize_value(v):
    """Convert any pandas/numpy NA-like value to None; leave everything else as-is."""
    if v is None:
        return None
    try:
        if pd.isna(v):
            return None
    except (TypeError, ValueError):
        pass
    return v


def _clean_records(df: pd.DataFrame) -> list:
    """Convert a DataFrame to JSON-safe records, replacing all NA-like values with None."""
    records = df.to_dict("records")
    return [{k: _sanitize_value(v) for k, v in row.items()} for row in records]


@app.get("/health")
def health():
    return {"status": "ok", "service": "Artemis_AR API"}


@app.get("/invoices")
def get_invoices():
    inv_path = DATA_DIR / "invoices.csv"
    cust_path = DATA_DIR / "customers.csv"
    _require_file(inv_path, "Run Day 1's generate_data.py first.")
    _require_file(cust_path, "Run Day 1's generate_data.py first.")

    invoices = pd.read_csv(inv_path)
    customers = pd.read_csv(cust_path)
    merged = invoices.merge(customers, on="customer_id", how="left")

    # attach current status from the real gated run state, if it exists
    state_path = DATA_DIR / "gated_run_state.json"
    if state_path.exists():
        states = load_states_from_file(state_path)
        status_map = {inv_id: s.status for inv_id, s in states.items()}
        remaining_map = {inv_id: s.remaining_amount for inv_id, s in states.items()}
        merged["current_status"] = merged["invoice_id"].map(status_map).fillna("overdue")
        merged["remaining_amount"] = merged["invoice_id"].map(remaining_map).fillna(merged["invoice_amount"])
    else:
        merged["current_status"] = "overdue"
        merged["remaining_amount"] = merged["invoice_amount"]

    return {"count": len(merged), "invoices": _clean_records(merged)}


@app.get("/invoices/{invoice_id}")
def get_invoice_detail(invoice_id: str):
    inv_path = DATA_DIR / "invoices.csv"
    cust_path = DATA_DIR / "customers.csv"
    _require_file(inv_path, "Run Day 1's generate_data.py first.")

    invoices = pd.read_csv(inv_path)
    customers = pd.read_csv(cust_path)

    inv_row = invoices[invoices["invoice_id"] == invoice_id]
    if inv_row.empty:
        raise HTTPException(status_code=404, detail=f"Invoice {invoice_id} not found.")

    invoice = {k: _sanitize_value(v) for k, v in inv_row.iloc[0].to_dict().items()}
    cust_row = customers[customers["customer_id"] == invoice["customer_id"]]
    customer = {k: _sanitize_value(v) for k, v in cust_row.iloc[0].to_dict().items()} if not cust_row.empty else {}

    # pull real action history + messages from the final audit trail, if built
    trail_path = DATA_DIR / "final_audit_trail.csv"
    history = []
    if trail_path.exists():
        trail = pd.read_csv(trail_path)
        inv_trail = trail[trail["invoice_id"] == invoice_id].sort_values("date")
        history = _clean_records(inv_trail)

    return {
        "invoice": invoice,
        "customer": customer,
        "action_history": history,
        "action_history_count": len(history),
    }


@app.get("/audit-trail")
def get_audit_trail(
    invoice_id: Optional[str] = None,
    action: Optional[str] = None,
    limit: int = Query(default=200, le=2000),
):
    trail_path = DATA_DIR / "final_audit_trail.csv"
    _require_file(trail_path, "Run Day 7's build_final_audit_trail.py first.")

    trail = pd.read_csv(trail_path)
    if invoice_id:
        trail = trail[trail["invoice_id"] == invoice_id]
    if action:
        trail = trail[trail["action"] == action]

    trail = trail.head(limit)
    return {"count": len(trail), "entries": _clean_records(trail)}


@app.get("/exceptions")
def get_exceptions():
    exc_path = DATA_DIR / "exception_report.csv"
    _require_file(exc_path, "Run Day 7's exception_report.py first.")

    df = pd.read_csv(exc_path)
    return {"count": len(df), "exceptions": _clean_records(df)}


@app.get("/metrics")
def get_metrics():
    state_path = DATA_DIR / "gated_run_state.json"
    _require_file(state_path, "Run Day 6's run_gated_simulation.py and resolve_approvals.py first.")

    states = load_states_from_file(state_path)
    total_original = sum(s.original_amount for s in states.values())
    total_recovered = sum(
        s.original_amount - s.remaining_amount for s in states.values()
    )

    status_counts = {}
    for s in states.values():
        status_counts[s.status] = status_counts.get(s.status, 0) + 1

    action_counts = {}
    trail_path = DATA_DIR / "final_audit_trail.csv"
    if trail_path.exists():
        trail = pd.read_csv(trail_path)
        contact_actions = trail[trail["action"].notna() &
                                 ~trail["action"].isin(["promise_resolution", "gated_pending_approval"])]
        action_counts = contact_actions["action"].value_counts().to_dict()

    message_stats = {}
    if trail_path.exists() and "message_source" in trail.columns:
        message_stats = trail["message_source"].value_counts(dropna=True).to_dict()

    return {
        "total_invoices": len(states),
        "total_original_amount": round(total_original, 2),
        "total_recovered": round(total_recovered, 2),
        "recovery_rate_pct": round(100 * total_recovered / total_original, 1) if total_original else 0,
        "status_breakdown": status_counts,
        "action_breakdown": action_counts,
        "message_source_breakdown": message_stats,
    }


@app.get("/")
def root():
    return {
        "service": "Artemis_AR API",
        "endpoints": [
            "/health", "/invoices", "/invoices/{invoice_id}",
            "/audit-trail", "/exceptions", "/metrics",
        ],
        "docs": "/docs",
    }